<?php
/**
 * PaymentRefundOperationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  daxslab\enzona\payment
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PaymentAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace daxslab\enzona\payment;

/**
 * PaymentRefundOperationsTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentRefundOperations
 * @package     daxslab\enzona\payment
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentRefundOperationsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentRefundOperations"
     */
    public function testPaymentRefundOperations()
    {
    }

    /**
     * Test attribute "transaction_uuid"
     */
    public function testPropertyTransactionUuid()
    {
    }

    /**
     * Test attribute "status_code"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "status_denom"
     */
    public function testPropertyStatusDenom()
    {
    }

    /**
     * Test attribute "transaction_created_at"
     */
    public function testPropertyTransactionCreatedAt()
    {
    }

    /**
     * Test attribute "transaction_updated_at"
     */
    public function testPropertyTransactionUpdatedAt()
    {
    }

    /**
     * Test attribute "transaction_signature"
     */
    public function testPropertyTransactionSignature()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "transaction_description"
     */
    public function testPropertyTransactionDescription()
    {
    }

    /**
     * Test attribute "transaction_denom"
     */
    public function testPropertyTransactionDenom()
    {
    }

    /**
     * Test attribute "transaction_code"
     */
    public function testPropertyTransactionCode()
    {
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "avatar"
     */
    public function testPropertyAvatar()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }
}
